# Generated by Django 5.0.6 on 2024-06-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='appointment_id',
            field=models.IntegerField(default=27),
        ),
    ]
