# Generated by Django 5.0.6 on 2024-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_medical_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ac', 'AC Room'), ('non_ac', 'Non-AC Room'), ('general', 'General Room')], max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
