# Generated by Django 5.0.6 on 2024-06-27 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.room'),
        ),
    ]
