# Generated by Django 5.0.6 on 2024-06-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_medical_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
