# Generated by Django 5.0.6 on 2024-06-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_room_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AddField(
            model_name='room',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
