# Generated by Django 5.0.6 on 2024-06-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_remove_room_is_available_room_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('AC', 'AC Room'), ('Non-AC', 'Non-AC Room'), ('General', 'General Room')], default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
