# Generated by Django 5.0.6 on 2024-06-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_remove_room_type_room_room_type_alter_room_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available_quantity',
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('ac', 'AC Room'), ('non_ac', 'Non-AC Room'), ('general', 'General Room')], max_length=20),
        ),
    ]
