# Generated by Django 5.0.6 on 2024-06-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_medical_admit_date_medical_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='patient',
            field=models.CharField(default=2, max_length=100),
        ),
    ]
