# Generated by Django 5.0.6 on 2024-06-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='medical',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='app2.medical'),
        ),
    ]
