# Generated by Django 5.0.6 on 2024-06-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_staff_delete_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='status',
        ),
    ]
