# Generated by Django 5.0.6 on 2024-06-14 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_remove_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status1',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
