# Generated by Django 5.0.6 on 2024-06-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_staff_status1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='status1',
        ),
    ]
