# Generated by Django 5.0.6 on 2024-06-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('department', models.CharField(max_length=20)),
                ('staff_type', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
