# Generated by Django 5.0.6 on 2024-06-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(default='Gandhinagar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.CharField(default='INDIA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='experience',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(default='no', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='graduation_year',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='languages',
            field=models.CharField(default='Hindi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='No', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='medical_license',
            field=models.CharField(default='Notavailable', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='medical_school',
            field=models.CharField(default='NO', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(default='00000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization',
            field=models.CharField(default='ALL', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='submission_date',
            field=models.DateField(default='2024-06-18'),
            preserve_default=False,
        ),
    ]
