# Generated by Django 5.0.6 on 2024-06-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('department', models.CharField(max_length=20)),
                ('staff_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='on', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('medical_license', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=120)),
                ('experience', models.IntegerField()),
                ('medical_school', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=255)),
                ('publications', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateField()),
                ('submitted_registration', models.BooleanField(default=False)),
            ],
        ),
    ]
