# Generated by Django 5.0.6 on 2024-06-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_alter_staff_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('blood_group', models.CharField(max_length=20)),
                ('sugar', models.CharField(max_length=20)),
                ('concerns', models.CharField(max_length=200)),
            ],
        ),
    ]
