# Generated by Django 5.0.6 on 2024-06-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='user_id',
        ),
    ]
