# Generated by Django 5.0.6 on 2024-06-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_rename_user_patient_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
    ]
